version: 2
general:
  branches:
    only:
     - master

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
         name: Install Rust
         command: "rustup install stable"
      - run:
          name: Stable Build
          command: |
            cd bitinfo
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
