# a comment
stpm:
   description: a crazy current sensor
   registers:
      DSP_CR3:
         description: dsp control reg 3
         bit_width: 32
         fields:
            ZCR_SEL:
               description: zero crossing config
               start: 14
               width: 2
               preferred_format: bin
            ZCR_EN:
               start: 16
               negated: false
               patterns:
                  0b0: CLK
                  0b1: ZCR
      DSP_EV2:
         description: the dsp event reg 2
         bit_width: 32
         registers:
            ph1 + ph2:
               description: info for both phases
               preferred_format: binary
               registers:
                  power sign:
                     fields:
                        active:
                           start: 0
                        reactive:
                           start: 1
                  energy overflow:
                     fields:
                        active:
                           start: 2
                        reactive:
                           start: 3

