# a comment
test-class1:
  class1:
   name: "class 1"
  class2:
   name: "class 2"

stpm:
   description: "a crazy current sensor"
   ranges:
      DSP_REG1:
         bit_width: 32

# - stpm:
#    - DSP_REG1:
#       width: 32
#       masks:
#          - 0: one bit
#          - 1-4: range of three
#          - 5-7: rest of a byte
#    - DPS_REG2:
#       width: 8
#       masks:
#          - 0: a bit
#          - 1: another bit
# - class2:
#    - class2-l1:
#       # assumed to be u32?
#       masks:
#          - 0: a bit
# - class3:
#    - class3-l1:
#       class3-l2:
#          # assumed to be u32?
#          masks:
#             - 0: a bit
