# a comment
STPM:
   description: a crazy current sensor
   registers:
      DSP_CR3:
         description: dsp control reg 3
         bit_width: 32
         fields:
            ZCR_SEL:
               description: zero crossing config
               start: 14
               width: 2
               preferred_format: bin
            ZCR_EN:
               start: 16
               negated: false
               patterns:
                  0b0: CLK
                  0b1: ZCR
      DSP_EV2:
         description: the dsp event reg 2
         preferred_format: binary
         bit_width: 32
         fields:
            power sign ph1+2 active:
               start: 0
            power sign ph1+2 reactive:
               start: 1
            energy overflow ph 1+2 active:
               start: 2
            energy overflow ph 1+2 reactive:
               start: 3

